name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v2

      - name: Utilisation de node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Naviger dans le répertoire cypress
        run: cd cypress

      - name: Installation des dépendances
        run: npm install

      - name: Exécuter les tests
        run: npx cypress run
